### ISSUE TITLE
Receiving "Contact request failed" on first authorize after partner app install

### ISSUE THREAD

**Issue by harunsmrkovic** [digime/digime-sdk-android#16]
SDK Version: 3.0.0

Sometimes we get an alert saying "Contract Request Failed"

Log from the partner app when it happens
```
2019-10-03 21:15:24.760 16894-16894/com.mobileubdiapp E/DigiMeSDK: There was a problem launching the consent request activity.
2019-10-03 21:15:24.768 16894-16894/com.mobileubdiapp I/DigiMeSDK: Starting fetch of session data.
```

Issue is always reproducible if partner app is freshly installed.

Other than this, it happens sometimes, but there is no pattern.

**Comment by JacobKingDev** [comment]
We know exactly what is causing this now and are actively working on a fix.

**Comment by JacobKingDev** [comment]
This has been fixed and will be made available in the digi.me client version 4.1.3.
