### ISSUE TITLE
Receiving 2 accounts for a user that has 1 account

### ISSUE THREAD

**Issue by harunsmrkovic** [digime/digime-sdk-android#28]
## Checklist
- [x] I’m using the latest version of the digi.me Private Sharing SDK.
- [x] I'm using the latest version of the digi.me App.
- [x] I've searched for existing [GitHub issues](https://github.com/digime/digime-sdk-android/issues)
- [x] I've looked for existing answers in the [SDK Documentation](https://digime.github.io/digime-sdk-android/index.html) and [Developer FAQs](https://digime.freshdesk.com/support/solutions/9000115894) 
- [x] This issue does not relate to security and can be disclosed publicly on Github. 

**It is possible this issue is present on both platforms, saw it on Android so reporting here**

## Environment
Describe your development environment here. Please provide as much information as you can, noting the following details if possible:
- Kotlin Version: `X.X.X`
- Android SDK Version: `2.0.2-UBDI`
- Installation Platform & Version: `[Gradle/Maven]` version `X.X.X`
## Goals
What are you trying to achieve? 
Get correct state of accounts in sync update
## Expected Results
What do you expect to happen?
Get only 1 account for Finance (32), because I have only 1 in my digi.me
## Actual Results
What actually happened?
I get 2 accounts for Finance (32), with two unique `identifier`s.
## Steps to Reproduce
What are the steps necessary to reproduce this issue?
Call getSessionFileList for digi.me library that contains these account IDs: `32_6Ma4mmZyrzhwAQX81gq8hddyv0V790tabopJ8`, `32_a36605c18ecb2d6bd4242ed1eb624b26`
## Code Samples & Details
If possible, please provide a code sample and any additional details to help us identify this issue. 

Here is an example of a response we receive

```
32_6Ma4mmZyrzhwAQX81gq8hddyv0V790tabopJ8:
identifier: “32_6Ma4mmZyrzhwAQX81gq8hddyv0V790tabopJ8”
syncState: “partial”
__proto__: Object
32_a36605c18ecb2d6bd4242ed1eb624b26:
identifier: “32_a36605c18ecb2d6bd4242ed1eb624b26”
syncState: “partial”
__proto__: Object
```

**Comment by olileung** [comment]
Hi @harunsmrkovic, using the getSessionAccounts() call (to get the accounts.json file), are you able to confirm how many accounts return and if these match the ones you've given?

**Comment by harunsmrkovic** [comment]
Got info from @vkirlic that this has been fixed and will be included in the next release
