### ISSUE TITLE
DMEAppCommunicator shared instance accessed before initialization

### ISSUE THREAD

**Issue by harunsmrkovic** [digime/digime-sdk-android#36]
## Checklist
- [x] I’m using the latest version of the digi.me Private Sharing SDK.
- [x] I'm using the latest version of the digi.me App.
- [x] I've searched for existing [GitHub issues](https://github.com/digime/digime-sdk-android/issues)
- [x] I've looked for existing answers in the [SDK Documentation](https://digime.github.io/digime-sdk-android/index.html) and [Developer FAQs](https://digime.freshdesk.com/support/solutions/9000115894) 
- [x] This issue does not relate to security and can be disclosed publicly on Github. 
## Environment
Describe your development environment here. Please provide as much information as you can, noting the following details if possible:
- Kotlin Version: `X.X.X`
- Android SDK Version: `2.1.0`
- Installation Platform & Version: `[Gradle/Maven]` version `X.X.X`
## Goals
What are you trying to achieve? 
Not sure, I think user tried to link source (authorization call)
## Expected Results
What do you expect to happen?
User does not get a crash/error
## Actual Results
What actually happened?
User got a crash/error
## Steps to Reproduce
What are the steps necessary to reproduce this issue?
Not sure, I think try to Link a source in UBDI app
## Code Samples & Details
If possible, please provide a code sample and any additional details to help us identify this issue. 
```
Console
03:38:55
E/AndroidRuntime( 465): at com.mobileubdiapp.MainActivity.onActivityResult(MainActivity.java:34)
Console
03:38:55
E/AndroidRuntime( 465): at me.digi.sdk.interapp.DMEAppCommunicator.getSharedInstance(Unknown Source:2)
Console
03:38:55
E/AndroidRuntime( 465): at me.digi.sdk.interapp.DMEAppCommunicator$Companion.getSharedInstance(DMEAppCommunicator.kt:27)
Console
03:38:55
E/AndroidRuntime( 465): Caused by: me.digi.sdk.DMESDKError$CommunicatorNotInitialized: DMEAppCommunicator shared instance accessed before initialization.
```

**Comment by JacobKingDev** [comment]
After investigation, this isn't a problem in the SDK itself, but with where it is being initialised in the partner app. The most likely cause is the callback for `onActivityResult` is being executed before a `DMEClient` object is initialised. Steps should be taken to ensure that this cannot happen.
